#!/bin/bash
ID=$(xdpyinfo | grep focus | cut -f4 -d " ")
PID=$(($(xprop -id $ID | grep -m 1 PID | cut -d " " -f 3) + 2))
if [ -e "/proc/$PID/cwd" ]
then
    echo $PID
    i3-sensible-terminal -e "cd $(readlink /proc/$PID/cwd) && /bin/bash" 
else
    i3-sensible-terminal
fi
